version: '3.8'

services:
  s3server:
    image: scality/s3server
    container_name: S3AniRun
    ports:
      - "8000:8000"
    environment:
      - port=8000
      - accessKey=5e806973-626b-4a2f-ba82-d99d9a995eae
      - secretKey=eb303786-3e5b-4e74-bee0-49e993ccdf45
      - bucket=bucket-anirun
    volumes:
      - /path/to/store/data:/usr/src/app/localData
    restart: always